<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Rossina.Modules.Products.Presentation</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Rossina.Modules.Catalog.Application\Rossina.Modules.Catalog.Application.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

</Project>
